version: "3"

services:
  order-service:
    restart: always
    build: ./order-service
    image: neutr0nian/foodify-order-service:1.0.0
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - PORT=3000
      - MQ_HOST=rabbitmq
      - MONGO_URI=mongo #use your mongo cluster or localhost mongo db
      - MONGO_HOST=mongo
      - SLEEP_TIME=20000
    ports:
      - "3000:3000"

  restaurant-service:
    restart: always
    build: ./restaurant-service
    image: neutr0nian/foodify-restaurant-service:1.0.0
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MQ_HOST=rabbitmq
      - MONGO_URI=mongo #use your mongo cluster or localhost mongo db
      - MONGO_HOST=mongo
      - PREFETCH_COUNT=3
      - SLEEP_TIME=20000

  email-service:
    restart: always
    build: ./email-service
    image: neutr0nian/foodify-email-service:1.0.0
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOST=rabbitmq
      - PREFETCH_COUNT=3
      - EMAIL_ID=test@gmail.com #your email id
      - EMAIL_PWD=test1234 #your email password
      - EMAIL_SERVICE=gmail #email service
      - SLEEP_TIME=20000

  mongo:
    image: mongo:4.2
    logging:
      driver: none
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.8.9
    logging:
      driver: none
    ports:
      - "5672:5672"
